# Generated by Django 2.0.6 on 2018-08-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back_camera', models.DecimalField(decimal_places=2, max_digits=10)),
                ('front_camera', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resolution_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resolution_2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('screen_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('battery', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pre_release_demand', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quarter', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
